#!/bin/bash

DOT_DIR="$HOME/.config/dot"
DOT_FILE="$DOT_DIR/dotfile"

if [[ $1 == "reverse" ]]; then
    mkdir -p "$DOT_DIR"
    cd "$DOT_DIR"
    while IFS= read -r line
    do
        line_array=($line)
        sys_file=$(eval echo ${line_array[0]})
        rel_repo_dir=$(eval echo ${line_array[1]})
        abs_repo_dir="$DOT_DIR/$rel_repo_dir"
        filename=$(basename $sys_file)
	abs_repo_file="$abs_repo_dir/$filename"
        sys_dir=$(dirname $sys_file)

	if [ -f $abs_repo_file ]; then
            if [ ! -d $sys_dir ]; then
                echo "Directory ${sys_dir} not found. Creating directory."
		mkdir -p $sysdir
            fi
	    echo "Copying from ${abs_repo_file} to ${sys_dir}"
	    cp ${abs_repo_file} ${sys_dir}
        else
            echo "Error ${abs_repo_file} not found. Skipping."
        fi
    done < "$DOT_FILE"
else
    if [ -f $DOT_FILE ]; then
        mkdir -p "$DOT_DIR"
        cd "$DOT_DIR"
        while IFS= read -r line
        do
            line_array=($line)
	    sys_file=$(eval echo ${line_array[0]})
            rel_repo_dir=$(eval echo ${line_array[1]})
            abs_repo_dir="$DOT_DIR/$rel_repo_dir"

            if [ -f $sys_file ]; then
                mkdir -p "${abs_repo_dir}"
                echo "Copying ${sys_file} to ${abs_repo_dir}"
                cp ${sys_file} ${abs_repo_dir}
            else
                echo "ERROR: ${sys_file} not found. Skipping."
            fi
        done < "$DOT_FILE"
    else
        echo "File $DOT_FILE does not exist."
    fi
fi

